// Generated by provision-sitecore-component (manifest: related-content-card) — handoff contract for /implement-build-pack.
import type { Field, LinkField } from '@sitecore-content-sdk/nextjs';
import type { ComponentProps } from 'lib/component-props';

export type RelatedContentCardFields = {
  // TODO(provision): Droptree reference — type as the referenced item shape used by this app's Content SDK version (verify the SDK surface), then render from the referenced item's fields.
  pageReference: unknown;
  cardTitleOverride?: Field<string>;
  ctaLink?: LinkField;
  // TODO(provision): Checkbox field — markup is design-driven; read the raw value.
  featured?: Field<boolean>;
  // TODO(provision): Number field — markup is design-driven; read the raw value.
  displayOrder?: Field<number>;
  // TODO(provision): Unmapped Sitecore field type "Custom Badge Picker" — type and render per the app's conventions.
  customBadge?: Field<unknown>;
};

export type RelatedContentCardProps = ComponentProps & {
  fields?: RelatedContentCardFields;
};
