// Generated by provision-sitecore-component (manifest: related-content-card) — scaffold filled in by /implement-build-pack.
import { Link, Text } from '@sitecore-content-sdk/nextjs';
import type { RelatedContentCardProps } from './RelatedContentCard.types';

const RelatedContentCard = (props: RelatedContentCardProps) => {
  const { page, fields } = props;
  const { isEditing } = page.mode;

  if (!fields && !isEditing) {
    return null;
  }

  const { pageReference, cardTitleOverride, ctaLink, featured, displayOrder, customBadge } = fields ?? {};

  return (
    <div data-component="related-content-card">
      {/* TODO(provision): scaffold only — layout, semantics, and styling come from the Build Pack via /implement-build-pack. */}
      {/* TODO(provision): pageReference — Droptree reference — type as the referenced item shape used by this app's Content SDK version (verify the SDK surface), then render from the referenced item's fields. */}
      <Text editable={isEditing} field={cardTitleOverride} />
      <Link editable={isEditing} field={ctaLink} />
      {/* TODO(provision): featured — Checkbox field — markup is design-driven; read the raw value. */}
      {/* TODO(provision): displayOrder — Number field — markup is design-driven; read the raw value. */}
      {/* TODO(provision): customBadge — Unmapped Sitecore field type "Custom Badge Picker" — type and render per the app's conventions. */}
    </div>
  );
};

export default RelatedContentCard;
