"use strict";

/**
 * TSX scaffold emitter. Pure — no I/O. Byte-deterministic output.
 *
 * emitTypes(manifest, resolved) → string   (ComponentName.types.ts)
 * emitComponent(manifest) → string         (ComponentName.tsx)
 *
 * Emits the house-pattern handoff pair the frontend pipeline consumes: the types file
 * is the exact rendering-boundary contract (field names, optionality, SDK wrapper
 * types — guaranteed to mirror the CMS because the same manifest creates the template);
 * the component file is a bare-bones scaffold that /implement-build-pack fills in
 * place. Contract doc: skills/provision-sitecore-component/references/tsx-template.md
 *
 * Two modes:
 * - datasource: rendering.datasourceTemplate names a manifest template → props carry
 *   `fields` from the component datasource (the AwardCard-style contract).
 * - page: no datasource-backed rendering → fields live on the page item; the scaffold
 *   types the contract and leaves the page-item access as a marked TODO.
 */

const { isPlainObject } = require("./util.cjs");
const { resolveType } = require("./type-map.cjs");

const SDK_MODULE = "@sitecore-content-sdk/nextjs";

/** Renderer → SDK component name (value import). */
const RENDERERS = { text: "Text", richtext: "RichText", image: "NextImage", link: "Link" };

/**
 * Pick the contract template and mode for the scaffold:
 * a rendering whose datasourceTemplate names a manifest template → datasource mode on
 * that template; otherwise the first role:"datasource" template (datasource mode) when
 * a rendering with a datasource is declared; otherwise page mode on the first template.
 */
function resolveContract(manifest) {
  const templates = manifest.templates;
  const rendering = isPlainObject(manifest.rendering) ? manifest.rendering : null;
  if (rendering && rendering.datasourceTemplate !== undefined) {
    const named = templates.find((t) => t.name === rendering.datasourceTemplate);
    if (named) return { mode: "datasource", template: named };
    const firstDatasource = templates.find((t) => t.role === "datasource");
    if (firstDatasource) return { mode: "datasource", template: firstDatasource };
  }
  return { mode: "page", template: templates[0] };
}

/** Flatten the contract template's fields in manifest order, with resolved type rows. */
function contractFields(template) {
  const out = [];
  for (const section of template.sections) {
    for (const field of section.fields) {
      out.push({ ...field, row: resolveType(field.sitecoreType) });
    }
  }
  return out;
}

function emitTypes(manifest, resolved) {
  const { mode, template } = resolveContract(manifest);
  const fields = contractFields(template);
  const component = manifest.component;

  const sdkImports = [...new Set(fields.flatMap((f) => f.row.typeImports))].sort();
  const lines = [];
  lines.push(`// Generated by provision-sitecore-component (manifest: ${manifest.slug}) — handoff contract for /implement-build-pack.`);
  if (sdkImports.length > 0) {
    lines.push(`import type { ${sdkImports.join(", ")} } from '${SDK_MODULE}';`);
  }
  lines.push(`import type { ComponentProps } from '${resolved.componentPropsImport}';`);
  lines.push("");
  if (mode === "page") {
    lines.push(`// Page-driven contract: these fields live on the page item (template "${template.name}"), not a component datasource.`);
  }
  lines.push(`export type ${component}Fields = {`);
  for (const f of fields) {
    if (f.row.todoNote) {
      lines.push(`  // TODO(provision): ${f.row.todoNote}`);
    }
    lines.push(`  ${f.name}${f.required === true ? "" : "?"}: ${f.row.tsType};`);
  }
  lines.push("};");
  lines.push("");
  if (mode === "datasource") {
    lines.push(`export type ${component}Props = ComponentProps & {`);
    lines.push(`  fields?: ${component}Fields;`);
    lines.push("};");
  } else {
    lines.push(`export type ${component}Props = ComponentProps;`);
  }
  lines.push("");
  return lines.join("\n");
}

function rendererLine(field, indent) {
  const { row, name } = field;
  if (row.renderer === "todo") {
    return `${indent}{/* TODO(provision): ${name} — ${row.todoNote} */}`;
  }
  const component = RENDERERS[row.renderer];
  const extra = row.renderer === "richtext" ? ' className="rtf"' : "";
  return `${indent}<${component}${extra} editable={isEditing} field={${name}} />`;
}

function emitComponent(manifest) {
  const { mode, template } = resolveContract(manifest);
  const fields = contractFields(template);
  const component = manifest.component;

  const usedRenderers = [...new Set(fields.map((f) => RENDERERS[f.row.renderer]).filter(Boolean))].sort();
  const lines = [];
  lines.push(`// Generated by provision-sitecore-component (manifest: ${manifest.slug}) — scaffold filled in by /implement-build-pack.`);
  if (usedRenderers.length > 0) {
    lines.push(`import { ${usedRenderers.join(", ")} } from '${SDK_MODULE}';`);
  }
  if (mode === "page") {
    lines.push(`import type { ${component}Fields, ${component}Props } from './${component}.types';`);
  } else {
    lines.push(`import type { ${component}Props } from './${component}.types';`);
  }
  lines.push("");
  lines.push(`const ${component} = (props: ${component}Props) => {`);
  if (mode === "datasource") {
    lines.push("  const { page, fields } = props;");
    lines.push("  const { isEditing } = page.mode;");
  } else {
    lines.push("  const { page } = props;");
    lines.push("  const { isEditing } = page.mode;");
    lines.push("");
    lines.push("  // TODO(provision): page-driven component — its fields live on the page item, not a datasource.");
    lines.push("  // Resolve them from the page's route/layout data per this app's conventions, then remove this placeholder.");
    lines.push(`  const fields: ${component}Fields | undefined = undefined;`);
  }
  lines.push("");
  lines.push("  if (!fields && !isEditing) {");
  lines.push("    return null;");
  lines.push("  }");
  lines.push("");
  lines.push(`  const { ${fields.map((f) => f.name).join(", ")} } = fields ?? {};`);
  lines.push("");
  lines.push("  return (");
  lines.push(`    <div data-component="${manifest.slug}">`);
  lines.push("      {/* TODO(provision): scaffold only — layout, semantics, and styling come from the Build Pack via /implement-build-pack. */}");
  for (const f of fields) {
    lines.push(rendererLine(f, "      "));
  }
  lines.push("    </div>");
  lines.push("  );");
  lines.push("};");
  lines.push("");
  lines.push(`export default ${component};`);
  lines.push("");
  return lines.join("\n");
}

module.exports = { emitTypes, emitComponent, resolveContract, contractFields };
