// Generated by provision-sitecore-component (manifest: people-detail-masthead) — handoff contract for /implement-build-pack.
import type { Field, ImageField, RichTextField } from '@sitecore-content-sdk/nextjs';
import type { ComponentProps } from 'lib/component-props';

// Page-driven contract: these fields live on the page item (template "People Detail Page"), not a component datasource.
export type PeopleDetailMastheadFields = {
  personName: Field<string>;
  personJobTitle: Field<string>;
  profileImage: ImageField;
  // TODO(provision): Date field — render/format is design-driven; no default SDK renderer is assumed.
  roleStartDate?: Field<string>;
  biographyText: RichTextField;
};

export type PeopleDetailMastheadProps = ComponentProps;
