// Generated by provision-sitecore-component (manifest: people-detail-masthead) — scaffold filled in by /implement-build-pack.
import { NextImage, RichText, Text } from '@sitecore-content-sdk/nextjs';
import type { PeopleDetailMastheadFields, PeopleDetailMastheadProps } from './PeopleDetailMasthead.types';

const PeopleDetailMasthead = (props: PeopleDetailMastheadProps) => {
  const { page } = props;
  const { isEditing } = page.mode;

  // TODO(provision): page-driven component — its fields live on the page item, not a datasource.
  // Resolve them from the page's route/layout data per this app's conventions, then remove this placeholder.
  const fields: PeopleDetailMastheadFields | undefined = undefined;

  if (!fields && !isEditing) {
    return null;
  }

  const { personName, personJobTitle, profileImage, roleStartDate, biographyText } = fields ?? {};

  return (
    <div data-component="people-detail-masthead">
      {/* TODO(provision): scaffold only — layout, semantics, and styling come from the Build Pack via /implement-build-pack. */}
      <Text editable={isEditing} field={personName} />
      <Text editable={isEditing} field={personJobTitle} />
      <NextImage editable={isEditing} field={profileImage} />
      {/* TODO(provision): roleStartDate — Date field — render/format is design-driven; no default SDK renderer is assumed. */}
      <RichText className="rtf" editable={isEditing} field={biographyText} />
    </div>
  );
};

export default PeopleDetailMasthead;
